spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
    #静态资源路径
    static-path-pattern: /**

server:
  port: 8080
mybatis-plus:
    type-aliases-package: com.joe.entity
    mapper-locations: classpath:mappers/*.xml
