# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis-plus:
  #\u6307\u660Emapper.xml\u626B\u63CF\u4F4D\u7F6E(classpath \u4EE3\u8868\u7F16\u8BD1\u540E\u7C7B\u6587\u4EF6\u6839\u76EE\u5F55)
  mapper-locations: classpath:/mapper/**Mapper.xml
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
